config/routes.rb
PovertyIndicators::Application.routes.draw do
  resources :poverty_indicators, only: :index do
    collection do
      get :indicator_by_state
      get :correlations
      get :comparisons
    end
  end

  root to: 'poverty_indicators#indicator_by_state'
end

app/models/correlation.rb
class Correlation < ActiveRecord::Base
end

app/models/correlations.rb
class Correlations
  attr_reader :indicators, :comparison_indicator

  def initialize indicators, comparison_indicator
    @comparison_indicator = comparison_indicator
    @indicators = indicators
  end

  def table
    @indicators.map do |i|
      [i, Statistics.correlation(records.map(&i.to_sym), records.map(&@comparison_indicator.to_sym))] rescue [i, nil]
    end
  end

  def records
    @records ||= PovertyIndicator.all
  end
end

app/models/highchart_map.rb
class HighchartMap < Hash
  @@state_keys = {
    Aguascalientes: 'mx-ag',
    :'Baja California' => 'mx-bc',
    :'Baja California Sur' => 'mx-bs',
    Campeche: 'mx-cm',
    Chiapas: 'mx-cs',
    Chihuahua: 'mx-ch',
    :'Coahuila de Zaragoza' => 'mx-co',
    Colima: 'mx-cl',
    :'Distrito Federal' => 'mx-df',
    Durango: 'mx-dg',
    Guanajuato: 'mx-gj',
    Guerrero: 'mx-gr',
    Hidalgo: 'mx-hg',
    Jalisco: 'mx-ja',
    :'Michoacán de Ocampo' => 'mx-mi',
    Morelos: 'mx-mo',
    México: 'mx-mx',
    Nayarit: 'mx-na',
    :'Nuevo León' => 'mx-nl',
    Oaxaca: 'mx-oa',
    Puebla: 'mx-pu',
    Querétaro: 'mx-qt',
    :'Quintana Roo' => 'mx-qr',
    :'San Luis Potosí' => 'mx-sl',
    Sinaloa: 'mx-si',
    Sonora: 'mx-so',
    Tabasco: 'mx-tb',
    Tamaulipas: 'mx-tm',
    Tlaxcala: 'mx-tl',
    :'Veracruz de Ignacio de la Llave' => 'mx-ve',
    Yucatán: 'mx-yu',
    Zacatecas: 'mx-za'
  }

  def self.prepare_data records
    records.map { |key, value| { 'hc-key' => @@state_keys[key], value: value } }
  end
end

app/models/indicator_by_state.rb
class IndicatorByState
  extend ActiveModel::Naming
  include ActiveModel::Conversion

  attr_accessor :formula, :indicator

  def initialize attributes = {}
    attributes.each do |name, value|
      send "#{name}=", value
    end
  end

  def values
    @values ||= records.each_with_object({}) { |r, memo| memo[r.nom_ent.to_sym] = r.send(@indicator) }
  end

  def empty?
    !@indicator && !@formula
  end


  private

  def records
    PovertyIndicator.
      select([PovertyIndicator.arel_table[@indicator].send(@formula).as(@indicator), :nom_ent]).
      group(:nom_ent)
  end
end

app/models/indicator_comparison.rb
class IndicatorComparison
  extend ActiveModel::Naming
  include ActiveModel::Conversion

  attr_accessor :indicator1, :indicator2

  def initialize attributes = {}
    attributes.each do |name, value|
      send "#{name}=", value
    end
  end

  def values
    @values ||= compute_correlations
  end

  def empty?
    !@indicator && !@indicator2
  end

  def correlation
    Statistics.correlation(records.map(&@indicator1.to_sym), records.map(&@indicator2.to_sym))
  end

  private

  def compute_correlations
    records.group_by { |p| p.nom_ent }.each_with_object({}) do |r, memo|
      memo[r.first.to_sym] = Statistics.correlation(r.last.map(&@indicator1.to_sym), r.last.map(&@indicator2.to_sym))
    end
  end

  def records
    @records ||= PovertyIndicator.select([@indicator1, @indicator2, :nom_ent]).to_a
  end
end

app/models/municipality_graph.rb
class MunicipalityGraph
  extend ActiveModel::Naming
  include ActiveModel::Conversion

  attr_accessor :formula, :indicator

  def initialize attributes = {}
    attributes.each do |name, value|
      send "#{name}=", value
    end
  end


  def records
    @records ||= PovertyIndicator.
      select([PovertyIndicator.arel_table[@indicator].send(@formula).as(@indicator), :nom_ent]).
      group(:nom_ent)
  end
end

app/models/poverty_indicator.rb
class PovertyIndicator < ActiveRecord::Base

  def self.indicators
    PovertyIndicator.column_names - %w(id ent nom_ent clave_mun nom_mun)
  end

  def self.indicators_for_correlations
    indicators - %w(pobreza pobreza_e pobreza_m)
  end
end

app/models/statistics.rb
module Statistics

  def Statistics.correlation x, y
    sum_x = x.inject :+
    sum_y = y.inject :+
    sum_x_square = x.inject(0) { |acc, v| acc + v ** 2 }
    sum_y_square = y.inject(0) { |acc, v| acc + v ** 2 }
    sum_xy = x.zip(y).inject(0) { |acc, v| acc + v[0] * v[1] }
    n = x.size

    ((n * sum_xy) - (sum_x * sum_y)) /
      (Math.sqrt((n * sum_x_square) - (sum_x ** 2)) * Math.sqrt((n * sum_y_square) - (sum_y ** 2)))
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/poverty_indicators_controller.rb
class PovertyIndicatorsController < ApplicationController
  def index
  end

  def indicator_by_state
    @indicator = IndicatorByState.new params[:indicator_by_state] || {}
  end

  def correlations
    @correlations = Correlation.all.order('(value IS NULL), ABS(value) desc').to_a
  end

  def comparisons
    @comparison = IndicatorComparison.new params[:indicator_comparison] || {}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/poverty_indicators_helper.rb
module PovertyIndicatorsHelper

  def formulas
    %w(maximum minimum average sum)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title><%= t :poverty_indicators %></title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js",
                               "https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to t(:poverty_indicators), root_path, class: "navbar-brand" %>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li>
            <%= link_to t(:by_state), indicator_by_state_poverty_indicators_path %>
          </li>
          <li>
            <%= link_to t(:comparison), comparisons_poverty_indicators_path %>
          </li>
          <li>
            <%= link_to t(:correlations), correlations_poverty_indicators_path %>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, :class => "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable" do %>
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= msg %>
      <% end %>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/poverty_indicators/_comparison_form.html.erb
<%= form_for @comparison, url: comparisons_poverty_indicators_path, method: :get do |f| %>

  <div class="row">
    <div class="col-xs-5">
      <label for="indicator"><%= "#{t :indicator} 1:" %></label>
    </div>

    <div class="col-xs-5">
      <label for="indicator"><%= "#{t :indicator} 2:" %></label>
    </div>
  </div>

  <div class="row">

    <div class="col-xs-5">
      <%= f.select :indicator1,
                   options_for_select(PovertyIndicator.indicators.map { |i| [t(i, scope: :indicators), i] }, @comparison.indicator1),
                   {},
                   class: 'form-control', id: 'indicator' %>
    </div>

    <div class="col-xs-5">
      <%= f.select :indicator2,
                   options_for_select(PovertyIndicator.indicators.map { |i| [t(i, scope: :indicators), i] }, @comparison.indicator2),
                   {},
                   class: 'form-control', id: 'indicator' %>
    </div>

    <div class="col-xs-2">
      <%= f.button t(:show),
                   class: 'btn btn-default',
                   data: { disable_with: '...' } %>
    </div>
  </div>

<% end %>

app/views/poverty_indicators/_correlations_table.html.erb
<table class="table table-condensed">
  <thead>
    <tr>
      <th><%= t :indicator %></th>
      <th><%= t :correlation_with_indicator, indicator: t(comparison_indicator, scope: :indicators) %></th>
    </tr>
  </thead>
  <tbody>
  <% @correlations.
       select { |c| c.comparison_indicator == comparison_indicator }.
       each do |correlation| %>
    <tr>
      <td><%= t correlation.indicator, scope: :indicators %></td>
      <td><%= number_with_precision correlation.value, delimiter: ',' %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/poverty_indicators/_form.html.erb
<%= form_for @indicator, url: indicator_by_state_poverty_indicators_path, method: :get do |f| %>

  <div class="row">
    <div class="col-xs-5">
      <label for="indicator"><%= "#{t :indicator}:" %></label>
    </div>

    <div class="col-xs-2">
      <%= content_tag :label,
                      t(:formula),
                      title: t(:formula_instructions),
                      class: 'hover',
                      id: 'instructions',
                      data: { placement: 'bottom' } %>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-5">
      <%= f.select :indicator,
                   options_for_select(PovertyIndicator.indicators.map { |i| [t(i, scope: :indicators), i] }, @indicator.indicator),
                   {},
                   class: 'form-control', id: 'indicator' %>
    </div>

    <div class="col-xs-2">
      <%= f.select :formula,
                   options_for_select(formulas.map { |formula| [t(formula, scope: :formulas), formula] }, @indicator.formula),
                   {},
                   class: 'form-control', id: 'formula' %>
    </div>

    <div class="col-xs-2">
      <button type="submit" class="btn btn-default"><%= t :show %></button>
    </div>
  </div>

<% end %>

<script>
  $(function() {
    $('#instructions').tooltip({ html: true });
  });
</script>

app/views/poverty_indicators/comparisons.html.erb
<div class="page-header">
  <h1><%= t :indicator_comparison %></h1>
</div>

<%= render 'comparison_form' %>

<% unless @comparison.empty? %>

  <blockquote class="well large-separator">
    <p class="lead">
      <%= "#{t :correlation}: #{number_with_precision @comparison.correlation}" %>
    </p>
  </blockquote>

  <div class="row separator">
    <div class="col-xs-12">
      <ul class="nav nav-tabs" role="tablist">
        <li class="active">
          <a href="#map" role="tab" data-toggle="tab"><%= t :map %></a>
        </li>
        <li>
          <a href="#table" role="tab" data-toggle="tab"><%= t :table %></a>
        </li>
      </ul>

      <div class="tab-content separator">

        <div class="tab-pane" id="table">
          <table class="table table-condensed">
            <thead>
              <tr>
                <th>
                  <%= "#{t @comparison.indicator1, scope: :indicators} vs #{t @comparison.indicator2, scope: :indicators}" %>
                </th>
                <th>
                  <%= t :correlation %>
                </th>
              </tr>
            </thead>

            <tbody>
              <% @comparison.values.sort_by { |_, value| -value.abs }.each do |key, value| %>

                <tr>
                  <td><%= key %></td>
                  <td><%= number_with_precision value %></td>
                </tr>

              <% end %>
            </tbody>
          </table>
        </div>

        <div class="tab-pane active" id="map">
          <div id="map_container"></div>
        </div>
      </div>
    </div>
  </div>

  <script>
    $(function () {

      var data = <%= raw HighchartMap.prepare_data(@comparison.values).to_json %>;

      $('#map_container').highcharts('Map', {
        title : {
          text : '<%= "#{t @comparison.indicator1, scope: :indicators} vs #{t @comparison.indicator2, scope: :indicators}" %>'
        },
        mapNavigation: {
          enabled: true
        },
        colorAxis: {
          min: null,
          max: null
        },
        series : [{
          data : data,
          mapData: Highcharts.maps['countries/mx/mx-all'],
          joinBy: 'hc-key',
          name: '<%= "#{t @comparison.indicator1, scope: :indicators} vs #{t @comparison.indicator2, scope: :indicators}" %>'
        }]
      });
    });
  </script>

<% end %>

app/views/poverty_indicators/correlations.html.erb
<div class="page-header">
  <h1><%= t :correlations_with_poverty_indicators_html %></h1>
</div>

<div class="row">
  <div class="col-xs-12">

    <ul class="nav nav-tabs" role="tablist">
      <li class="active">
        <a href="#poverty" role="tab" data-toggle="tab">
          <%= t :pobreza, scope: :indicators %>
        </a>
      </li>

      <li>
        <a href="#poverty-e" role="tab" data-toggle="tab">
          <%= t :pobreza_e, scope: :indicators %>
        </a>
      </li>
      <li>
        <a href="#poverty-m" role="tab" data-toggle="tab">
          <%= t :pobreza_m, scope: :indicators %>
        </a>
      </li>
    </ul>

    <div class="tab-content separator">

      <div class="tab-pane active" id="poverty">
        <%= render 'correlations_table', comparison_indicator: 'pobreza' %>
      </div>

      <div class="tab-pane" id="poverty-e">
        <%= render 'correlations_table', comparison_indicator: 'pobreza_e' %>
      </div>

      <div class="tab-pane" id="poverty-m">
        <%= render 'correlations_table', comparison_indicator: 'pobreza_m' %>
      </div>
    </div>
  </div>
</div>

app/views/poverty_indicators/index.html.erb
<div class="page-header">
  <h1><%= t :menu %></h1>
</div>

<div class="row">
  <%= link_to t(:indicator_by_state), indicator_by_state_poverty_indicators_path, class: 'btn btn-default' %>
</div>

app/views/poverty_indicators/indicator_by_state.html.erb
<div class="page-header">
  <h1><%= t :indicator_by_state %></h1>
</div>

<%= render 'form' %>

<% unless @indicator.empty? %>

  <div class="row separator">
    <div class="col-xs-12">
      <ul class="nav nav-tabs" role="tablist">
        <li class="active">
          <a href="#map" role="tab" data-toggle="tab"><%= t :map %></a>
        </li>
        <li>
          <a href="#table" role="tab" data-toggle="tab"><%= t :table %></a>
        </li>
      </ul>

      <div class="tab-content separator">

        <div class="tab-pane" id="table">
          <table class="table table-condensed">
            <thead>
            <tr>
              <th><%= t :state %></th>
              <th><%= t @indicator.indicator, scope: :indicators %></th>
            </tr>
            </thead>

            <tbody>
            <% @indicator.values.sort_by { |_, value| -value }.each do |key, value| %>

              <tr>
                <td><%= key %></td>
                <td><%= number_with_precision value, delimiter: ',' %></td>
              </tr>

            <% end %>
            </tbody>
          </table>
        </div>

        <div class="tab-pane active" id="map">
          <div id="map_container"></div>
        </div>
      </div>
    </div>
  </div>

  <script>
    $(function () {

      var data = <%= raw HighchartMap.prepare_data(@indicator.values).to_json %>;

      $('#map_container').highcharts('Map', {
        title : {
          text : '<%= t @indicator.indicator, scope: :indicators %>'
        },
        mapNavigation: {
          enabled: true
        },
        colorAxis: {
          min: null,
          max: null
        },
        series : [{
          data : data,
          mapData: Highcharts.maps['countries/mx/mx-all'],
          joinBy: 'hc-key',
          name: '<%= t @indicator.indicator, scope: :indicators %>'
        }]
      });
    });
  </script>

<% end %>

app/views/poverty_indicators/municipality_graph.html.erb
<div class="page-header">
  <h1><%= t :indicator_by_state %></h1>
</div>

<div class="row">
  <%= render 'form' %>
</div>

<ul class="nav nav-tabs" role="tablist">
  <li class="active">
    <a href="#table" role="tab" data-toggle="tab"><%= t :table %></a>
  </li>
  <li>
    <a href="#map" role="tab" data-toggle="tab"><%= t :map %></a>
  </li>
</ul>

<div class="tab-content">

  <div class="tab-pane active" id="table">
    <table class="table table-condensed">
      <thead>
      <tr>
        <td><%= t :state %></td>
        <td><%= t @graph.indicator, scope: :indicators %></td>
      </tr>
      </thead>

      <tbody>
      <% @graph.records.each do |row| %>

        <tr>
          <td><%= row.nom_ent %></td>
          <td><%= number_with_delimiter row.send(@graph.indicator) %></td>
        </tr>

      <% end %>
      </tbody>
    </table>
  </div>

  <div class="tab-pane" id="map">mapa</div>
</div>